"""FastAPI wrapper around NeMo Guardrails for Concierge."""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Annotated, Any, Literal
from uuid import UUID

import structlog
from fastapi import Depends, FastAPI, Header, HTTPException, status
from nemoguardrails import LLMRails, RailsConfig
from pydantic import BaseModel, ConfigDict, Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict

from app.policies import check_input_policy, check_output_policy, redact_pii

logger = structlog.get_logger(__name__)

CONFIG_DIR = Path(__file__).resolve().parents[1] / "config"


class Settings(BaseSettings):
    """Runtime settings for the NeMo guardrails sidecar."""

    model_config = SettingsConfigDict(extra="forbid")

    log_level: str = "INFO"
    guardrails_service_token: SecretStr = SecretStr("")
    nemo_enabled: bool = True


class GuardrailRequest(BaseModel):
    """Request body for input/output rail checks."""

    tenant_id: UUID
    message: str = Field(..., min_length=1, max_length=4000)
    tenant_config: dict[str, Any] = Field(default_factory=dict)

    model_config = ConfigDict(extra="forbid")


class GuardrailResponse(BaseModel):
    """Guardrails decision response."""

    decision: Literal["allow", "refuse"]
    reason: str | None = None
    safe_text: str | None = None
    triggered_rules: list[str] = Field(default_factory=list)


def get_settings() -> Settings:
    """Return sidecar settings."""
    return Settings()


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Load NeMo Guardrails once at startup."""
    settings = get_settings()
    log_level = getattr(logging, settings.log_level.upper(), logging.INFO)

    structlog.configure(wrapper_class=structlog.make_filtering_bound_logger(log_level))

    app.state.rails = None

    if settings.nemo_enabled:
        config = RailsConfig.from_path(str(CONFIG_DIR))
        app.state.rails = LLMRails(config)
        logger.info("guardrails.nemo_loaded", config_dir=str(CONFIG_DIR))
    else:
        logger.warning("guardrails.nemo_disabled")

    yield

    logger.info("guardrails.stopped")


app = FastAPI(
    title="Concierge NeMo Guardrails Sidecar",
    version="0.1.0",
    lifespan=lifespan,
)


async def require_service_token(
    settings: Annotated[Settings, Depends(get_settings)],
    authorization: Annotated[str | None, Header()] = None,
) -> None:
    """Require service-token authentication when configured."""
    expected = settings.guardrails_service_token.get_secret_value()

    if not expected:
        return

    if authorization != f"Bearer {expected}":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid service token",
        )


def _looks_like_refusal(text: str) -> bool:
    """Detect a refusal generated by NeMo rails."""
    lowered = text.lower()
    refusal_markers = (
        "i can't help",
        "i cannot help",
        "i can’t help",
        "not allowed",
        "cannot provide",
        "can't provide",
        "violates",
        "security rules",
        "platform security",
    )
    return any(marker in lowered for marker in refusal_markers)


async def _run_nemo_check(message: str) -> str | None:
    """Run the message through NeMo if the rails object is loaded."""
    rails: LLMRails | None = app.state.rails

    if rails is None:
        return None

    response = await rails.generate_async(
        messages=[{"role": "user", "content": message}]
    )

    if isinstance(response, dict):
        content = response.get("content")
        if isinstance(content, str):
            return content

    if isinstance(response, str):
        return response

    return str(response)


@app.get("/healthz", include_in_schema=False)
async def healthz() -> dict[str, str]:
    """Health check endpoint."""
    return {"status": "ok"}


@app.post(
    "/check_input",
    response_model=GuardrailResponse,
    dependencies=[Depends(require_service_token)],
)
async def check_input(request: GuardrailRequest) -> GuardrailResponse:
    """Check visitor input using deterministic rails plus NeMo Guardrails."""
    deterministic = check_input_policy(
        message=request.message,
        tenant_config=request.tenant_config,
    )

    if deterministic.decision == "refuse":
        return GuardrailResponse(
            decision="refuse",
            reason=deterministic.reason,
            safe_text=None,
            triggered_rules=deterministic.triggered_rules,
        )

    nemo_response = await _run_nemo_check(request.message)

    if nemo_response and _looks_like_refusal(nemo_response):
        return GuardrailResponse(
            decision="refuse",
            reason=nemo_response,
            safe_text=None,
            triggered_rules=["nemo.input_rail"],
        )

    return GuardrailResponse(
        decision="allow",
        reason=None,
        safe_text=deterministic.safe_text or redact_pii(request.message),
        triggered_rules=[],
    )


@app.post(
    "/check_output",
    response_model=GuardrailResponse,
    dependencies=[Depends(require_service_token)],
)
async def check_output(request: GuardrailRequest) -> GuardrailResponse:
    """Check assistant output before returning it to the visitor."""
    deterministic = check_output_policy(
        message=request.message,
        tenant_config=request.tenant_config,
    )

    if deterministic.decision == "refuse":
        return GuardrailResponse(
            decision="refuse",
            reason=deterministic.reason,
            safe_text=None,
            triggered_rules=deterministic.triggered_rules,
        )

    safe_text = deterministic.safe_text or redact_pii(request.message)

    return GuardrailResponse(
        decision="allow",
        reason=None,
        safe_text=safe_text,
        triggered_rules=deterministic.triggered_rules,
    )
